const words = [
    "abandon","cabinet","fabric","jacket","narrow","rabbit","ugly",
    "ability","cable","face","jail","nation","race","ultimate",
    "able","cage","fact","jam","native","radio","umbrella",
    "about","cake","factor","jar","nature","rail","uncle",
    "above","calculate","factory","jaw","near","rain","under",
    "abroad","calendar","faculty","jazz","neat","raise","unit",
    "absolute","call","fade","jealous","necessary","range","universe",
    "academic","calm","fail","jelly","neck","rare","university",
    "accept","camera","fair","jewel","need","rate","unknown",
    "access","camp","faith","job","negative","rather","unless",
    "accident","campaign","fall","join","negotiate","reach","until",
    "accompany","campus","false","joint","neighbor","react","unusual",
    "account","can","familiar","joke","neither","read","up",
    "accurate","canal","family","journal","nerve","ready","upon",
    "achieve","cancel","famous","journey","nest","real","upper",
    "acid","cancer","fan","joy","net","reality","urban",
    "across","candidate","fancy","judge","network","realize","urge",
    "act","candle","fantastic","juice","neutral","really","urgent",
    "action","candy","far","jump","never","rear","us",
    "active","canvas","farm","junior","new","reason","use",
    "activity","cap","fashion","jury","news","rebel","useful",
    "actor","capability","fast","just","next","recall","user",
    "actual","capacity","fat","justice","nice","receipt","usual",
    "adapt","capital","fatal","justify","night","receive","utility",
    "add","captain","fate","keen","nine","recent","vacation",
    "addition","capture","father","keep","no","reception","vague",
    "address","car","fault","kettle","noble","recipe","valid",
    "adequate","carbon","favor","key","nobody","recognize","valley",
    "adjust","card","favorite","kick","noise","recommend","valuable",
    "admire","care","fear","kid","none","record","value",
    "admit","career","feature","kill","nor","recover","vanish",
    "adopt","careful","federal","kind","normal","red","variety",
    "adult","cargo","fee","king","north","reduce","various",
    "advance","carpet","feed","kiss","nose","refer","vary",
    "advice","carry","feel","kitchen","not","reflect","vast",
    "affair","case","fellow","knee","note","reform","vegetable",
    "affect","cash","female","knife","nothing","refuse","vehicle",
    "afford","cast","fence","knock","notice","regard","venture",
    "afraid","castle","ferry","knot","notion","region","verb",
    "after","casual","festival","know","novel","register","verdict",
    "again","cat","fetch","knowledge","now","regular","version",
    "against","catch","fever","label","nuclear","reject","vessel",
    "age","category","few","labor","number","relate","veteran",
    "agency","cause","fiber","lack","numerous","relation","via",
    "agent","cave","fiction","ladder","nurse","relative","victim",
    "ago","cease","field","lady","nut","relax","victory",
    "agree","ceiling","fierce","lake","oak","release","video",
    "ahead","celebrate","fight","lamp","obey","relief","view",
    "aid","cell","figure","land","object","religion","village",
    "aim","cement","file","landscape","oblige","rely","violence",
    "air","center","fill","lane","observe","remain","virtual",
    "alarm","central","film","language","obtain","remark","virus",
    "album","century","final","lantern","obvious","remedy","visible",
    "alcohol","ceremony","finance","lap","occasion","remember","vision",
    "alert","certain","find","large","occupy","remind","visit",
    "alien","chain","fine","laser","occur","remote","vital",
    "alike","chair","finger","last","odd","render","vocal",
    "alive","chairman","finish","late","off","rent","voice",
    "all","challenge","fire","latter","offend","repair","volume",
    "alliance","chamber","firm","laugh","offer","repeat","vote",
    "allow","champion","first","launch","office","replace","voyage",
    "almost","chance","fish","law","officer","reply","wage",
    "alone","change","fist","lawyer","official","report","wagon",
    "along","channel","fit","lay","often","represent","wait",
    "aloud","chapter","five","layer","oil","request","wake",
    "alpha"
];

export const getSentence = (length: number = 3): string => {
    const sentence = [];
    for (let i = 0; i < length; i++) {
        sentence.push(words[Math.floor(Math.random() * words.length)]);
    }
    return sentence.join(" ");
}